global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
  - job_name: 'metrics-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics-server:9101']
