name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags: ["v*.*.*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: make i

      - name: Lint & Typecheck
        run: make fmt && make lint && make typecheck

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Build Docker image (local tag)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          echo "${IMAGE}" > image.txt
          docker build -t "${IMAGE}" app

      - name: Save image as TAR
        run: |
          IMAGE=$(cat image.txt)
          docker save "${IMAGE}" -o image.tar

      - name: Upload image.tar
        uses: actions/upload-artifact@v4
        with:
          name: app-image-tar
          path: image.tar
          retention-days: 7

      - name: Push to GHCR on tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}"
          docker tag $(cat image.txt) "${IMAGE}"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push "${IMAGE}"
